package com.example.fitme

import android.content.Context
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import org.json.JSONObject

data class AppStrings(
    val langCode: String = "ES",
    val navHome: String = "Inicio",
    val navPerfil: String = "Perfil",
    val navMenu: String = "Menú",
    val navRutina: String = "Rutina",
    val navRacha: String = "Racha",
    val helloPrefix: String = "Hola",
    val defaultAthleteLabel: String = "Atleta",
    val homeMotivation: String = "¡A por el entrenamiento de hoy!",
    val streakBannerDay: String = "día",
    val streakBannerDays: String = "días",
    val streakBannerSuffix: String = "de racha!",
    val streakBannerKeepGoing: String = "¡No lo rompas! Registra tu check de hoy",
    val whatTodayTitle: String = "¿Qué hacemos hoy?",
    val cardPerfilTitle: String = "Mi Perfil",
    val cardPerfilDesc: String = "Peso, altura e IMC",
    val cardMenuTitle: String = "Menú semanal",
    val cardMenuDesc: String = "Tu plan de nutrición",
    val cardRutinaTitle: String = "Rutina del día",
    val cardRutinaDesc: String = "Ejercicios de hoy",
    val cardRachaTitle: String = "Mi Racha",
    val cardRachaDesc: String = "Días consecutivos",
    val logoutBtn: String = "Salir",
    val perfilTitle: String = "Mi Perfil",
    val defaultUserLabel: String = "Usuario",
    val emailLabel: String = "Email",
    val ageLabel: String = "Edad",
    val ageUnit: String = "años",
    val genderLabel: String = "Sexo",
    val goalLabel: String = "Objetivo",
    val physicalDataTitle: String = "Datos Físicos",
    val heightLabel: String = "Altura",
    val weightLabel: String = "Peso",
    val imcLabel: String = "IMC",
    val weightRecordsLabel: String = "Registros de peso:",
    val editPhysicalBtn: String = "Editar datos físicos",
    val pesoChartBtn: String = "📈 Peso",
    val imcChartBtn: String = "📊 IMC",
    val editPerfilTitle: String = "Editar Datos Físicos",
    val heightField: String = "Altura (cm)",
    val heightPlaceholder: String = "Ej: 175",
    val currentWeightField: String = "Peso actual (kg)",
    val weightPlaceholder: String = "Ej: 70.5",
    val ageField: String = "Edad",
    val agePlaceholder: String = "Ej: 22",
    val genderField: String = "Sexo",
    val genderPlaceholder: String = "Hombre / Mujer / Otro",
    val invalidHeightMsg: String = "Introduce una altura válida",
    val invalidWeightMsg: String = "Introduce un peso válido",
    val dataSavedOk: String = "✓ Datos guardados correctamente",
    val saveBtn: String = "Guardar",
    val backBtn: String = "Volver",
    val rutinaTitle: String = "Rutina del Día",
    val myPersonalRoutineLabel: String = "Mi Rutina Personalizada",
    val estimatedMinutes: String = "min estimados",
    val editBtnLabel: String = "✏️ Editar",
    val personalRoutinaActiveLabel: String = "📌 Rutina personalizada activa",
    val trainingDoneTodayMsg: String = "¡Entrenamiento completado hoy!",
    val markDoneBtn: String = "✓ Marcar como completado",
    val viewHistorialBtn: String = "Ver historial de entrenamientos",
    val seriesChip: String = "series",
    val repsChip: String = "reps",
    val restChip: String = "descanso",
    val menuSemanalTitle: String = "Menú Semanal",
    val personalMenuActiveLabel: String = "📌 Menú personalizado activo",
    val goalPrefix: String = "Objetivo:",
    val breakfastLabel: String = "🌅 Desayuno",
    val lunchLabel: String = "☀️ Almuerzo",
    val dinnerLabel: String = "🌙 Cena",
    val proteinSuffix: String = "g de proteína",
    val generalGoalLabel: String = "General",
    val rachaTitle: String = "Mi Racha",
    val dayLabel: String = "día",
    val daysLabel: String = "días",
    val streakMsg0: String = "¡Empieza hoy tu racha!",
    val streakMsg7: String = "¡Vas bien, sigue así!",
    val streakMsg30: String = "¡Racha increíble! 💪",
    val streakMsgLegend: String = "¡Leyenda! 🏆",
    val bestStreakLabel: String = "🏆 Mejor racha",
    val totalDaysLabel: String = "📅 Total días",
    val todayLabel: String = "Hoy",
    val noCheckYetMsg: String = "Aún no has registrado tu check",
    val exerciseCheckChip: String = "Ejercicio ✓",
    val dietCheckChip: String = "Dieta ✓",
    val registerCheckBtn: String = "✓ Registrar check de hoy",
    val viewCheckBtn: String = "Ver check de hoy",
    val dayHistoryTitle: String = "Historial de días",
    val noRegisteredDaysMsg: String = "Aún no hay días registrados.\nCompleta tu primer check.",
    val checkDiarioTitle: String = "Check Diario",
    val completedLabel: String = "completado",
    val exerciseSwitchTitle: String = "Ejercicio completado",
    val exerciseSwitchDesc: String = "Has realizado tu rutina de hoy",
    val dietSwitchTitle: String = "Dieta seguida",
    val dietSwitchDesc: String = "Has respetado tu plan de alimentación",
    val checkAlreadySavedMsg: String = "✓ Check de hoy ya guardado",
    val savedCorrectlyMsg: String = "✓ Guardado correctamente",
    val saveCheckBtn: String = "Guardar check del día",
    val backToRachaBtn: String = "Volver a Racha",
    val historialTitle: String = "Historial de Entrenamientos",
    val sessionsCompletedLabel: String = "sesiones completadas",
    val noTrainingYetMsg: String = "Aún no has completado\nningún entrenamiento.",
    val weightEvolutionTitle: String = "Evolución del Peso",
    val imcEvolutionTitle: String = "Evolución del IMC",
    val noRecordsYetMsg: String = "Sin registros aún.\nGuarda tu peso en Editar Perfil.",
    val need2RecordsMsg: String = "Necesitas al menos 2 registros\npara ver la gráfica.",
    val historyLabel: String = "Historial",
    val historyImcLabel: String = "Historial IMC",
    val noRecordsMsg: String = "Aún no hay registros.",
    val imcNoRecords: String = "Sin registros aún.",
    val imcNeed2: String = "Necesitas al menos 2 registros.",
    val underweightLabel: String = "Bajo peso",
    val normalLabel: String = "Normal",
    val overweightLabel: String = "Sobrepeso",
    val editMenuTitle: String = "Editar Menú Semanal",
    val editMenuHint: String = "Toca una comida para editarla. Los cambios se guardan al pulsar \"Guardar\".",
    val restoreDefaultMenuBtn: String = "↩ Restaurar menú predeterminado",
    val saveMenuBtn: String = "💾 Guardar menú",
    val backToMenuBtn: String = "Volver al menú",
    val foodFieldLabel: String = "Comida",
    val kcalFieldLabel: String = "Kcal",
    val proteinFieldLabel: String = "Prot (g)",
    val cancelBtn: String = "Cancelar",
    val editarRutinaTitle: String = "Editar mi Rutina",
    val editarRutinaHint: String = "Construye tu rutina eligiendo del catálogo o creando ejercicios propios",
    val loadDefaultRoutinePrefix: String = "⚡ Cargar rutina predeterminada:",
    val clearPersonalRoutineBtn: String = "🗑 Limpiar rutina personal",
    val myCurrentRoutinePrefix: String = "Mi Rutina",
    val exercisesCountSuffix: String = "ejercicios",
    val noExercisesYetMsg: String = "Aún no has añadido ejercicios.\nUsa el catálogo de abajo o carga una rutina predeterminada.",
    val addOwnExerciseTitle: String = "Añadir ejercicio propio",
    val exerciseNameFieldLabel: String = "Nombre del ejercicio",
    val seriesFieldLabel: String = "Series",
    val repsFieldLabel: String = "Reps",
    val restFieldLabel: String = "Descanso",
    val descriptionFieldLabel: String = "Descripción (opcional)",
    val addToRoutineBtn: String = "+ Añadir a mi rutina",
    val exerciseCatalogTitle: String = "Catálogo de ejercicios",
    val searchExercisePlaceholder: String = "Buscar ejercicio...",
    val backToRoutineBtn: String = "Volver a la rutina",
    val saveExerciseBtn: String = "Guardar",
    val deleteExerciseBtn: String = "Eliminar",
    val yourMainGoalLabel: String = "Tu objetivo principal",
    val yourBMILabel: String = "Tu IMC",
    val bmiRangesTitle: String = "Rangos de IMC",
    val continueBtn: String = "Continuar",
    val enterWeightHeightMsg: String = "Introduce tu peso y altura\npara ver tu IMC",
    val youHereMarker: String = "← tú",
    val goalMuscle: String = "Ganancia Muscular",
    val goalSport: String = "Mantenimiento Deportivo",
    val goalWeightLoss: String = "Pérdida de Peso",
    val descNoImc: String = "Introduce tu peso y altura en el perfil para recibir una recomendación personalizada basada en tu IMC.",
    val descUnderweight: String = "Tu IMC indica que estás por debajo del peso saludable. Te recomendamos un plan enfocado en ganar masa muscular con una dieta hipercalórica rica en proteínas.",
    val descNormal: String = "¡Enhorabuena! Tu IMC está en el rango saludable. Tu plan se centrará en mantener tu forma actual, mejorar el rendimiento deportivo y ganar fuerza funcional.",
    val descOverweight: String = "Tu IMC indica sobrepeso. Te recomendamos combinar cardio y entrenamiento de fuerza con una dieta hipocalórica equilibrada para reducir el porcentaje de grasa de forma saludable.",
    val descObese: String = "Tu IMC indica obesidad. Te recomendamos empezar con ejercicio de baja intensidad y una alimentación equilibrada. Consulta con un profesional de la salud antes de comenzar.",
    val imcUnderweight: String = "< 18.5  ·  Bajo peso",
    val imcNormal: String = "18.5 – 24.9  ·  Normal",
    val imcOverweight: String = "25 – 29.9  ·  Sobrepeso",
    val imcObese: String = "> 30  ·  Obesidad",
    val chooseFoodsTitle: String = "Elige tus alimentos",
    val selectPreferencesHint: String = "Selecciona tus preferencias fitness",
    val loginSubtitle: String = "Tu compañero de fitness",
    val usernameLoginLabel: String = "Usuario",
    val passwordLoginLabel: String = "Contraseña",
    val loginBtn: String = "Iniciar sesión",
    val loginErrorMsg: String = "Usuario o contraseña incorrectos",
    val noAccountLink: String = "¿No tienes cuenta? Créala ya",
    val createAccountTitle: String = "Crear Cuenta",
    val completeDetailsHint: String = "Completa tus datos para empezar",
    val usernameRegisterField: String = "Nombre de usuario *",
    val emailRegisterField: String = "Correo electrónico *",
    val passwordRegisterField: String = "Contraseña *",
    val ageRegisterField: String = "Edad *",
    val genderRegisterField: String = "Sexo (opcional)",
    val weightRegisterField: String = "Peso (kg) *",
    val heightRegisterField: String = "Altura (cm) *",
    val bmiAutoCalculatedMsg: String = "Tu objetivo se calculará automáticamente según tu IMC (peso + altura)",
    val fillAllRequiredMsg: String = "Por favor completa todos los campos obligatorios",
    val enterValidWeightMsg: String = "Introduce un peso válido (ej: 70.5)",
    val enterValidHeightMsg: String = "Introduce una altura válida (ej: 175)",
    val signupBtn: String = "Registrarse",
    val accountCreatedOkMsg: String = "¡Cuenta creada correctamente!",
    val nowCalculatingGoalMsg: String = "Ahora calcularemos tu objetivo según tu IMC",
    val continueRegisterBtn: String = "Continuar →",
    val alreadyAccountLink: String = "¿Ya tienes cuenta? Inicia sesión"
)

fun loadStrings(context: Context, isSpanish: Boolean): AppStrings {
    val fileName = if (isSpanish) "strings_es.json" else "strings_en.json"
    val json = context.assets.open(fileName).bufferedReader().use { it.readText() }
    val j = JSONObject(json)
    fun s(key: String, default: String) = j.optString(key, default)
    return AppStrings(
        langCode = s("langCode", if (isSpanish) "ES" else "EN"),
        navHome = s("navHome", "Inicio"),
        navPerfil = s("navPerfil", "Perfil"),
        navMenu = s("navMenu", "Menú"),
        navRutina = s("navRutina", "Rutina"),
        navRacha = s("navRacha", "Racha"),
        helloPrefix = s("helloPrefix", "Hola"),
        defaultAthleteLabel = s("defaultAthleteLabel", "Atleta"),
        homeMotivation = s("homeMotivation", "¡A por el entrenamiento de hoy!"),
        streakBannerDay = s("streakBannerDay", "día"),
        streakBannerDays = s("streakBannerDays", "días"),
        streakBannerSuffix = s("streakBannerSuffix", "de racha!"),
        streakBannerKeepGoing = s("streakBannerKeepGoing", "¡No lo rompas! Registra tu check de hoy"),
        whatTodayTitle = s("whatTodayTitle", "¿Qué hacemos hoy?"),
        cardPerfilTitle = s("cardPerfilTitle", "Mi Perfil"),
        cardPerfilDesc = s("cardPerfilDesc", "Peso, altura e IMC"),
        cardMenuTitle = s("cardMenuTitle", "Menú semanal"),
        cardMenuDesc = s("cardMenuDesc", "Tu plan de nutrición"),
        cardRutinaTitle = s("cardRutinaTitle", "Rutina del día"),
        cardRutinaDesc = s("cardRutinaDesc", "Ejercicios de hoy"),
        cardRachaTitle = s("cardRachaTitle", "Mi Racha"),
        cardRachaDesc = s("cardRachaDesc", "Días consecutivos"),
        logoutBtn = s("logoutBtn", "Salir"),
        perfilTitle = s("perfilTitle", "Mi Perfil"),
        defaultUserLabel = s("defaultUserLabel", "Usuario"),
        emailLabel = s("emailLabel", "Email"),
        ageLabel = s("ageLabel", "Edad"),
        ageUnit = s("ageUnit", "años"),
        genderLabel = s("genderLabel", "Sexo"),
        goalLabel = s("goalLabel", "Objetivo"),
        physicalDataTitle = s("physicalDataTitle", "Datos Físicos"),
        heightLabel = s("heightLabel", "Altura"),
        weightLabel = s("weightLabel", "Peso"),
        imcLabel = s("imcLabel", "IMC"),
        weightRecordsLabel = s("weightRecordsLabel", "Registros de peso:"),
        editPhysicalBtn = s("editPhysicalBtn", "Editar datos físicos"),
        pesoChartBtn = s("pesoChartBtn", "📈 Peso"),
        imcChartBtn = s("imcChartBtn", "📊 IMC"),
        editPerfilTitle = s("editPerfilTitle", "Editar Datos Físicos"),
        heightField = s("heightField", "Altura (cm)"),
        heightPlaceholder = s("heightPlaceholder", "Ej: 175"),
        currentWeightField = s("currentWeightField", "Peso actual (kg)"),
        weightPlaceholder = s("weightPlaceholder", "Ej: 70.5"),
        ageField = s("ageField", "Edad"),
        agePlaceholder = s("agePlaceholder", "Ej: 22"),
        genderField = s("genderField", "Sexo"),
        genderPlaceholder = s("genderPlaceholder", "Hombre / Mujer / Otro"),
        invalidHeightMsg = s("invalidHeightMsg", "Introduce una altura válida"),
        invalidWeightMsg = s("invalidWeightMsg", "Introduce un peso válido"),
        dataSavedOk = s("dataSavedOk", "✓ Datos guardados correctamente"),
        saveBtn = s("saveBtn", "Guardar"),
        backBtn = s("backBtn", "Volver"),
        rutinaTitle = s("rutinaTitle", "Rutina del Día"),
        myPersonalRoutineLabel = s("myPersonalRoutineLabel", "Mi Rutina Personalizada"),
        estimatedMinutes = s("estimatedMinutes", "min estimados"),
        editBtnLabel = s("editBtnLabel", "✏️ Editar"),
        personalRoutinaActiveLabel = s("personalRoutinaActiveLabel", "📌 Rutina personalizada activa"),
        trainingDoneTodayMsg = s("trainingDoneTodayMsg", "¡Entrenamiento completado hoy!"),
        markDoneBtn = s("markDoneBtn", "✓ Marcar como completado"),
        viewHistorialBtn = s("viewHistorialBtn", "Ver historial de entrenamientos"),
        seriesChip = s("seriesChip", "series"),
        repsChip = s("repsChip", "reps"),
        restChip = s("restChip", "descanso"),
        menuSemanalTitle = s("menuSemanalTitle", "Menú Semanal"),
        personalMenuActiveLabel = s("personalMenuActiveLabel", "📌 Menú personalizado activo"),
        goalPrefix = s("goalPrefix", "Objetivo:"),
        breakfastLabel = s("breakfastLabel", "🌅 Desayuno"),
        lunchLabel = s("lunchLabel", "☀️ Almuerzo"),
        dinnerLabel = s("dinnerLabel", "🌙 Cena"),
        proteinSuffix = s("proteinSuffix", "g de proteína"),
        generalGoalLabel = s("generalGoalLabel", "General"),
        rachaTitle = s("rachaTitle", "Mi Racha"),
        dayLabel = s("dayLabel", "día"),
        daysLabel = s("daysLabel", "días"),
        streakMsg0 = s("streakMsg0", "¡Empieza hoy tu racha!"),
        streakMsg7 = s("streakMsg7", "¡Vas bien, sigue así!"),
        streakMsg30 = s("streakMsg30", "¡Racha increíble! 💪"),
        streakMsgLegend = s("streakMsgLegend", "¡Leyenda! 🏆"),
        bestStreakLabel = s("bestStreakLabel", "🏆 Mejor racha"),
        totalDaysLabel = s("totalDaysLabel", "📅 Total días"),
        todayLabel = s("todayLabel", "Hoy"),
        noCheckYetMsg = s("noCheckYetMsg", "Aún no has registrado tu check"),
        exerciseCheckChip = s("exerciseCheckChip", "Ejercicio ✓"),
        dietCheckChip = s("dietCheckChip", "Dieta ✓"),
        registerCheckBtn = s("registerCheckBtn", "✓ Registrar check de hoy"),
        viewCheckBtn = s("viewCheckBtn", "Ver check de hoy"),
        dayHistoryTitle = s("dayHistoryTitle", "Historial de días"),
        noRegisteredDaysMsg = s("noRegisteredDaysMsg", "Aún no hay días registrados.\nCompleta tu primer check."),
        checkDiarioTitle = s("checkDiarioTitle", "Check Diario"),
        completedLabel = s("completedLabel", "completado"),
        exerciseSwitchTitle = s("exerciseSwitchTitle", "Ejercicio completado"),
        exerciseSwitchDesc = s("exerciseSwitchDesc", "Has realizado tu rutina de hoy"),
        dietSwitchTitle = s("dietSwitchTitle", "Dieta seguida"),
        dietSwitchDesc = s("dietSwitchDesc", "Has respetado tu plan de alimentación"),
        checkAlreadySavedMsg = s("checkAlreadySavedMsg", "✓ Check de hoy ya guardado"),
        savedCorrectlyMsg = s("savedCorrectlyMsg", "✓ Guardado correctamente"),
        saveCheckBtn = s("saveCheckBtn", "Guardar check del día"),
        backToRachaBtn = s("backToRachaBtn", "Volver a Racha"),
        historialTitle = s("historialTitle", "Historial de Entrenamientos"),
        sessionsCompletedLabel = s("sessionsCompletedLabel", "sesiones completadas"),
        noTrainingYetMsg = s("noTrainingYetMsg", "Aún no has completado\nningún entrenamiento."),
        weightEvolutionTitle = s("weightEvolutionTitle", "Evolución del Peso"),
        imcEvolutionTitle = s("imcEvolutionTitle", "Evolución del IMC"),
        noRecordsYetMsg = s("noRecordsYetMsg", "Sin registros aún.\nGuarda tu peso en Editar Perfil."),
        need2RecordsMsg = s("need2RecordsMsg", "Necesitas al menos 2 registros\npara ver la gráfica."),
        historyLabel = s("historyLabel", "Historial"),
        historyImcLabel = s("historyImcLabel", "Historial IMC"),
        noRecordsMsg = s("noRecordsMsg", "Aún no hay registros."),
        imcNoRecords = s("imcNoRecords", "Sin registros aún."),
        imcNeed2 = s("imcNeed2", "Necesitas al menos 2 registros."),
        underweightLabel = s("underweightLabel", "Bajo peso"),
        normalLabel = s("normalLabel", "Normal"),
        overweightLabel = s("overweightLabel", "Sobrepeso"),
        editMenuTitle = s("editMenuTitle", "Editar Menú Semanal"),
        editMenuHint = s("editMenuHint", "Toca una comida para editarla. Los cambios se guardan al pulsar \"Guardar\"."),
        restoreDefaultMenuBtn = s("restoreDefaultMenuBtn", "↩ Restaurar menú predeterminado"),
        saveMenuBtn = s("saveMenuBtn", "💾 Guardar menú"),
        backToMenuBtn = s("backToMenuBtn", "Volver al menú"),
        foodFieldLabel = s("foodFieldLabel", "Comida"),
        kcalFieldLabel = s("kcalFieldLabel", "Kcal"),
        proteinFieldLabel = s("proteinFieldLabel", "Prot (g)"),
        cancelBtn = s("cancelBtn", "Cancelar"),
        editarRutinaTitle = s("editarRutinaTitle", "Editar mi Rutina"),
        editarRutinaHint = s("editarRutinaHint", "Construye tu rutina eligiendo del catálogo o creando ejercicios propios"),
        loadDefaultRoutinePrefix = s("loadDefaultRoutinePrefix", "⚡ Cargar rutina predeterminada:"),
        clearPersonalRoutineBtn = s("clearPersonalRoutineBtn", "🗑 Limpiar rutina personal"),
        myCurrentRoutinePrefix = s("myCurrentRoutinePrefix", "Mi Rutina"),
        exercisesCountSuffix = s("exercisesCountSuffix", "ejercicios"),
        noExercisesYetMsg = s("noExercisesYetMsg", "Aún no has añadido ejercicios.\nUsa el catálogo de abajo o carga una rutina predeterminada."),
        addOwnExerciseTitle = s("addOwnExerciseTitle", "Añadir ejercicio propio"),
        exerciseNameFieldLabel = s("exerciseNameFieldLabel", "Nombre del ejercicio"),
        seriesFieldLabel = s("seriesFieldLabel", "Series"),
        repsFieldLabel = s("repsFieldLabel", "Reps"),
        restFieldLabel = s("restFieldLabel", "Descanso"),
        descriptionFieldLabel = s("descriptionFieldLabel", "Descripción (opcional)"),
        addToRoutineBtn = s("addToRoutineBtn", "+ Añadir a mi rutina"),
        exerciseCatalogTitle = s("exerciseCatalogTitle", "Catálogo de ejercicios"),
        searchExercisePlaceholder = s("searchExercisePlaceholder", "Buscar ejercicio..."),
        backToRoutineBtn = s("backToRoutineBtn", "Volver a la rutina"),
        saveExerciseBtn = s("saveExerciseBtn", "Guardar"),
        deleteExerciseBtn = s("deleteExerciseBtn", "Eliminar"),
        yourMainGoalLabel = s("yourMainGoalLabel", "Tu objetivo principal"),
        yourBMILabel = s("yourBMILabel", "Tu IMC"),
        bmiRangesTitle = s("bmiRangesTitle", "Rangos de IMC"),
        continueBtn = s("continueBtn", "Continuar"),
        enterWeightHeightMsg = s("enterWeightHeightMsg", "Introduce tu peso y altura\npara ver tu IMC"),
        youHereMarker = s("youHereMarker", "← tú"),
        goalMuscle = s("goalMuscle", "Ganancia Muscular"),
        goalSport = s("goalSport", "Mantenimiento Deportivo"),
        goalWeightLoss = s("goalWeightLoss", "Pérdida de Peso"),
        descNoImc = s("descNoImc", "Introduce tu peso y altura en el perfil para recibir una recomendación personalizada basada en tu IMC."),
        descUnderweight = s("descUnderweight", "Tu IMC indica que estás por debajo del peso saludable. Te recomendamos un plan enfocado en ganar masa muscular con una dieta hipercalórica rica en proteínas."),
        descNormal = s("descNormal", "¡Enhorabuena! Tu IMC está en el rango saludable. Tu plan se centrará en mantener tu forma actual, mejorar el rendimiento deportivo y ganar fuerza funcional."),
        descOverweight = s("descOverweight", "Tu IMC indica sobrepeso. Te recomendamos combinar cardio y entrenamiento de fuerza con una dieta hipocalórica equilibrada para reducir el porcentaje de grasa de forma saludable."),
        descObese = s("descObese", "Tu IMC indica obesidad. Te recomendamos empezar con ejercicio de baja intensidad y una alimentación equilibrada. Consulta con un profesional de la salud antes de comenzar."),
        imcUnderweight = s("imcUnderweight", "< 18.5  ·  Bajo peso"),
        imcNormal = s("imcNormal", "18.5 – 24.9  ·  Normal"),
        imcOverweight = s("imcOverweight", "25 – 29.9  ·  Sobrepeso"),
        imcObese = s("imcObese", "> 30  ·  Obesidad"),
        chooseFoodsTitle = s("chooseFoodsTitle", "Elige tus alimentos"),
        selectPreferencesHint = s("selectPreferencesHint", "Selecciona tus preferencias fitness"),
        loginSubtitle = s("loginSubtitle", "Tu compañero de fitness"),
        usernameLoginLabel = s("usernameLoginLabel", "Usuario"),
        passwordLoginLabel = s("passwordLoginLabel", "Contraseña"),
        loginBtn = s("loginBtn", "Iniciar sesión"),
        loginErrorMsg = s("loginErrorMsg", "Usuario o contraseña incorrectos"),
        noAccountLink = s("noAccountLink", "¿No tienes cuenta? Créala ya"),
        createAccountTitle = s("createAccountTitle", "Crear Cuenta"),
        completeDetailsHint = s("completeDetailsHint", "Completa tus datos para empezar"),
        usernameRegisterField = s("usernameRegisterField", "Nombre de usuario *"),
        emailRegisterField = s("emailRegisterField", "Correo electrónico *"),
        passwordRegisterField = s("passwordRegisterField", "Contraseña *"),
        ageRegisterField = s("ageRegisterField", "Edad *"),
        genderRegisterField = s("genderRegisterField", "Sexo (opcional)"),
        weightRegisterField = s("weightRegisterField", "Peso (kg) *"),
        heightRegisterField = s("heightRegisterField", "Altura (cm) *"),
        bmiAutoCalculatedMsg = s("bmiAutoCalculatedMsg", "Tu objetivo se calculará automáticamente según tu IMC (peso + altura)"),
        fillAllRequiredMsg = s("fillAllRequiredMsg", "Por favor completa todos los campos obligatorios"),
        enterValidWeightMsg = s("enterValidWeightMsg", "Introduce un peso válido (ej: 70.5)"),
        enterValidHeightMsg = s("enterValidHeightMsg", "Introduce una altura válida (ej: 175)"),
        signupBtn = s("signupBtn", "Registrarse"),
        accountCreatedOkMsg = s("accountCreatedOkMsg", "¡Cuenta creada correctamente!"),
        nowCalculatingGoalMsg = s("nowCalculatingGoalMsg", "Ahora calcularemos tu objetivo según tu IMC"),
        continueRegisterBtn = s("continueRegisterBtn", "Continuar →"),
        alreadyAccountLink = s("alreadyAccountLink", "¿Ya tienes cuenta? Inicia sesión")
    )
}

val LocalAppStrings = compositionLocalOf { AppStrings() }
val LocalIsSpanish = compositionLocalOf { true }
val LocalOnToggleLanguage = compositionLocalOf<() -> Unit> { {} }

@Composable
fun LanguageToggleButton(modifier: Modifier = Modifier) {
    val isSpanish = LocalIsSpanish.current
    val onToggle = LocalOnToggleLanguage.current
    Box(
        modifier = modifier
            .background(
                if (isSpanish) Color(0xFF00C853) else Color(0xFF1565C0),
                RoundedCornerShape(20.dp)
            )
            .clickable { onToggle() }
            .padding(horizontal = 14.dp, vertical = 8.dp),
        contentAlignment = Alignment.Center
    ) {
        Text(
            text = if (isSpanish) "ES" else "EN",
            color = Color.White,
            fontWeight = FontWeight.Bold
        )
    }
}

@Composable
fun GymBackground(overlay: Float = 0.78f, content: @Composable BoxScope.() -> Unit) {
    Box(modifier = Modifier.fillMaxSize()) {
        Image(
            painter = painterResource(id = R.drawable.gym_bg),
            contentDescription = null,
            contentScale = ContentScale.Crop,
            modifier = Modifier.fillMaxSize()
        )
        Box(modifier = Modifier.fillMaxSize().background(Color.Black.copy(alpha = overlay)))
        content()
    }
}
